### ISSUE TITLE
Outline view

### ISSUE THREAD

**Issue by ambyte** [x10sv/pml#7]
Can you add support [Outline view](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view)

**Comment by AngelinCalu** [comment]
I will look into it. 

For now I'm a bit stuck on adding [intellisense ](https://code.visualstudio.com/docs/editor/intellisense) functionality for variables

**Comment by ambyte** [comment]
> I will look into it.
> 
> For now I'm a bit stuck on adding [intellisense ](https://code.visualstudio.com/docs/editor/intellisense) functionality for variables

I will follow the updates
Good luck in development and thanks for the extension

**Comment by prvlaar** [comment]
Is it a question of adding: (microsoft example)
```
{
  "symbolOutline.doSort": false,
  "symbolOutline.sortOrder": [
    "Class",
    "Module",
    "Constant",
    "Interface",
    "*",
    "Constructor",
    "Function",
    "Method"
  ],
  "symbolOutline.expandNodes": [
    "Module",
    "Class",
    "Interface",
    "Namespace",
    "Object",
    "Package",
    "Struct"
  ],
  "symbolOutline.topLevel": [
    "*"
  ]
}
```
to your dictionary.json.
But then adjusted to follow: "define method/endmethod" and "define function/endfunction" blocks.

**Comment by AngelinCalu** [comment]
Hello @prvlaar, and thank you for your interest.

I've been quite busy lately, but I'll be happy to review and merge any changes to the extension.
Please feel free to submit a pull request with the proposed changes.

Thanks!

**Comment by AngelinCalu** [comment]
To my embarrassment, this was already working since 23 Oct 2019, even before you opened this issue: 
`provideDocumentSymbols` is both adding the "Go To Symbol" functionality and the outline view. 
I have packed the whole thing yesterday in a new version. Apologies for the late actions.

https://github.com/x10sv/pml/commit/7fa898938025b23a3cadbe3252e132eb2563f383#diff-45327f86d4438556066de133327f4ca2R142
